# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20180417_1717'),
        ('analytics', '0018_auto_20170615_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorAddedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(max_length=50)),
                ('advisor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Added_Advisor', to='student.Student')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Added', to='student.Student')),
            ],
        ),
    ]
