# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.CharField(default=-1, max_length=300),
        ),
    ]
